### PR TITLE
Updating link to project website

### PR DESCRIPTION
**Pull request by gnatih**

### CODE REVIEW

**Comment by shravan91** [comment]
What is this for @gnatih ?

**Comment by ndkcha** [comment]
@shravan91 it fixes the link to open-loo project. merging it.

**Comment by shravan91** [comment]
@ndkcha I think the links are still not fixed.

cc @gnatih @jimishio

**Comment by ndkcha** [comment]
I think, there is a problem with CNAME listing.
As far as i know, the default repository of every github pages site is `<orgname>.github.io` and other repositories are listed as `<orgname>.github.io/<repo-name>`. 
In our case, root github pages site doesnot point to "datameetamd.github.io" repo. but the other repositories, such as open-loo, is pointing to `datameedamd.github.io/open-loo`. but our CNAME for the website doesn't point to  `datameetamd.github.io`, resulting into linking problem.
I don't know much about how domain names work in github. But i guess, if we change the repo name back to datameetamd.github.io and CNAME records corresponding to it, I guess that will work.
Let's keep domain names and naming conventions related to that to future scope and focus more on projects and data. I will share the firebase details. I am yet to look into the public access part in firebase. But with the API key, anyone can feed the data.

**Comment by gnatih** [comment]
@ndkcha I agree with you. There was no need to rename the website repo. Also I have actually seen little data too.

**Comment by shravan91** [comment]
@ndkcha Thanks!!

Should I change the name of the website repo?

**Pull request merged**
